### PR TITLE
Fix default date format mapping

### PR DESCRIPTION
**Pull request by Huskydog9988**

### CODE REVIEW

**Comment by Liam-DeVoe** [comment]
does simply removing the mappings for `MM/dd/yy` and `HH:mm:ss` not work? I would prefer that if it does.

**Comment by Huskydog9988** [comment]
i think it does, and seems to be fine for me, but i just did this because thats what you agreed to on discord

**Comment by Liam-DeVoe** [comment]
well I thought this message implied I preferred them to be removed:

> the first thing I would try is simply remove the x and X mappings, HH/mm/ss all already have mappings so it may just work ™️

**Comment by Huskydog9988** [comment]
fair enough, i removed them

**Comment by Liam-DeVoe** [comment]
have also removed another locale-specific identifier, `%c`. lgtm

**Pull request merged**
